### ISSUE TITLE
Bikeshed on the API

### ISSUE THREAD

**Issue by jamestalmage** [tapjs/stack-utils#1]
I think most of the functions should take options objects instead of a list of args.

so 

``` js
stack.capture({limit: 1, startStackFunction: fn});
```

instead of

``` js
stack.capture(1, fn);
```

Almost every parameter is optional anyways, so it seems more sensible to do it that way.

// @isaacs @bcoe @sindresorhus

**Comment by sindresorhus** [comment]
:+1: Makes the code a lot more readable too.

**Comment by isaacs** [comment]
For very short argument lists, where the args are clearly differentiated by type, I actually prefer just using plain old args.  The other advantage is that it provides a natural resistance to increasing the size of the api.  (Adding one more positional arg hurts, but adding one more option feels easy.)

**Comment by jamestalmage** [comment]
Interesting thought. I barreled ahead and switched to an options object, but it's easy enough to change back.

I was thinking of some additional options though:

- `stripMessageLine: boolean`: Right now `clean` strips the message line off the top of the stack trace. That serves `tap` well since the message line is already transmitted as part of the yaml object, but maybe not other users who just want to print a beautified stack trace.

- `clean: boolean`: Right now `captureString` automatically calls clean. That may not serve everyone. An alternative to adding an option would be to stop doing it automatically and make people who want that behavior do: `stackUtils.clean(stackUtils.captureString(...))`.

**Comment by isaacs** [comment]
See this is what I'm talking about ;)

Once you have an options object, having only one or two options feels like you're not justifying the object enough.  It's almost impossible not to.  There's that object, right there, it's so easy to just add one more little thing to it.  So you add more options, more branches and combinations that are harder to test and document, etc.

I am not speaking as a saint who never does this, but as a sinner who knows the temptation and the costs all too well.
