### ISSUE TITLE
Fail to parseLine when path contains '('

### ISSUE THREAD

**Issue by jaridmargolin** [tapjs/stack-utils#23]
**Example:**

```js
stackUtils.parseLine('    at Context.<anonymous> (/Users/USER/Dropbox (Personal)/example/test.js:14:11)')
// => null

stackUtils.parseLine('    at Context.<anonymous> (/Users/USER/Dropbox/example/test.js:14:11)')
// => { line: 14, column: 11, file: '/Users/USER/Dropbox/example/test.js', function: 'Context.<anonymous>' }
```

Looking at the possible [permutations](https://github.com/v8/v8/wiki/Stack-Trace-API#appendix-stack-trace-format) I am not very confident in my ability to get a patch implemented 😟 Possibly someone with more experience would have time to look at this?

---

Additionally, I hit this issue trying to utilize another library as well ([stack-trace](https://github.com/felixge/node-stack-trace/blob/master/lib/stack-trace.js#L20)). I wonder if the parseLine functionality could be pulled out and utilized by both libraries in order to maximize reuse, improve consistency, and share workload? Just a thought.

**Comment by jaridmargolin** [comment]
The very well may be naive, but changing the matching pattern for location to not negate the `)` character appears to fix my issue while not breaking any of the existing tests.

line 215:
**before:** `'(?:eval at ([^ ]+) \\(([^\\)]+):(\\d+):(\\d+)\\), )?' +`
**after:** `'(?:eval at ([^ ]+) \\((.+):(\\d+):(\\d+)\\), )?' +`

line 219:
**before:**  `'(?:([^\\)]+):(\\d+):(\\d+)|(native))' +`
**after:** `'(?:(.+):(\\d+):(\\d+)|(native))' +`

**Comment by jamestalmage** [comment]
Actually creating a PR would allow easier review than trying to put the changes in a comment.

The issue seems legit. Start a PR with your proposed changes, and we can debate from there.
